apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: isr-internship
  labels:
    app: isr-internship-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: isr-internship-backend
  template:
    metadata:
      labels:
        app: isr-internship-backend
    spec:
      imagePullSecrets:
        - name: harbor-secret # Sesuaikan jika nama secret di namespace Anda berbeda
      containers:
        - name: backend
          image: registry.infrasvc.id/isr-internship/backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: backend-configmap
            - secretRef:
                name: backend-secret
