apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: isr-internship
spec:
  type: ClusterIP
  selector:
    app: isr-internship-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
