apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: isr-internship
spec:
  type: ClusterIP
  selector:
    app: isr-internship-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
